[package]
name = "trait_alias"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0" # MSRV

license = "MIT OR Apache-2.0"
repository = "https://github.com/lars-schumann/trait_alias"
# homepage = ""
# readme = "README.md"
description = "trait aliases in stable Rust"
# keywords = []

[dependencies]
